### ISSUE TITLE
HorseやRace に対して変更を加えるRPCの追加

### ISSUE THREAD

**Issue by Azuki-bar** [ueckoken/chofu-race-course#108]
現在、登録はできるが変更はできない
そもそも変更を加えるためのrpcを定義していないからである
ですので定義しましょう

**Comment by hutinoatari** [comment]
自動で変更することってできます？例えば`HorseDetail`の`histories`は手動よりもレースデータの更新に合わせて自動で変更すると嬉しい

**Comment by Azuki-bar** [comment]
`HorseDetail`の`histories`など一部に限れば、ある変更に伴って変更させることとはできると思います

**Comment by Azuki-bar** [comment]
まだRaceは追加されていないのでReOpen

**Comment by hutinoatari** [comment]
全部実装完了！
