### ISSUE TITLE
`editHorse`で馬名を空にして送るとバリデートエラーが出る

### ISSUE THREAD

**Issue by hutinoatari** [ueckoken/chofu-race-course#171]
値が入ってる項目だけ更新するようにしてほしい

**Comment by hutinoatari** [comment]
馬主名と写真は空でも通った

**Comment by Azuki-bar** [comment]
本件ですが、バリデータ実装前に入れた、バリデータを通過しないデータに対して変更を加えようとしたことが原因でした。
これに対してエラーが出るのは仕様とします。変更を加えたいときは一度削除して追加し直してください。
