### ISSUE TITLE
EditHorseRequestの仕様について

### ISSUE THREAD

**Issue by Azuki-bar** [ueckoken/chofu-race-course#179]
https://github.com/ueckoken/chofu-race-course/blob/main/docs/protobuf.md#edithorserequest
現在の仕様だとOptinoalなものに対して変更するとなっているが、Protocol buffer では未定義の値はデフォルト値を入れることにして定義する。
現在のEditHorseRequestの仕様だと、画像を登録することはできても画像を削除することができない。
削除したいならフラグを追加する必要がある。

**Comment by hutinoatari** [comment]
画像は
image => 更新
undefined => そのまま
null => 削除
って感じにできたら理想

**Comment by Azuki-bar** [comment]
undefinedもnullもprotobufを経由するとどちらも同じデフォルト値になってしまうんですよね
なので判別には使えないです

**Comment by Azuki-bar** [comment]
この件ですが画像を消すことを現状想定しないこととします。

理由
- SSGで競走馬データを入れているため、間違えて入れても反映までに時間がかかる（即時反映じゃない）ので入れ直してもよさそう
