### ISSUE TITLE
馬のフィールドの追加

### ISSUE THREAD

**Issue by hutinoatari** [ueckoken/chofu-race-course#55]
`HorseDetail`に`retire`(現役か抹消か)を追加する

**Comment by Azuki-bar** [comment]
抹消はどのようにして登録しますか？
https://github.com/ueckoken/chofu-race-course/blob/main/docs/protobuf.md#spec-v1-EditHorseRequest に入れますか？

**Comment by hutinoatari** [comment]
元々レース間の改造禁止を想定していた(抹消することでレースに出走できない代わりにパーツを再利用できるようになる)がそうでは無くなったので現役/抹消の概念が今あるか怪しい
closeしちゃっていいかも

**Comment by Azuki-bar** [comment]
closeしましょう。
